### ISSUE TITLE
Data is not persisted

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafeSystems/WeiPay#145]
**Describe the bug**
The app should remember that I have already accepted the terms, created an ethereum wallet, the selected coins, contacts... etc

**To Reproduce**
1. Accept the terms
2. Generate a wallet
3. Close app & Reopen

**Expected behavior**
Should remember all-state.

**Desktop (please complete the following information):**
 - The latest beta version.

**Smartphone (please complete the following information):**
 - Huawei P20 Pro

**Comment by ansermino** [comment]
Reproduced on OnePlus 3

**Comment by masterrom** [comment]
I believe this issue has been resolved and the data seems to persist on simulator and device ( May need some testing on Apple devices )

**Comment by ansermino** [comment]
When was the latest android release? Still getting the same behavior but wouldn't be shocked if I'm out of date

**Comment by ansermino** [comment]
?

**Comment by masterrom** [comment]
Yea, the app on android and IOS is not updated. This Issue has been resolved
